### ISSUE TITLE
注册问题

### ISSUE THREAD

**Issue by Orange12313** [tohsaka888/cxy-home#2]

**Comment by Orange12313** [comment]
使用邮箱注册完成时，刚出现设置用户名和密码界面，就跳转到了登陆界面，导致账户没有用户名和密码无法登录。

**Comment by tohsaka888** [comment]
> 使用邮箱注册完成时，刚出现设置用户名和密码界面，就跳转到了登陆界面，导致账户没有用户名和密码无法登录。

可能是在没有输入用户名密码时就点击了注册,再次注册由于数据库已有邮箱,无法重复注册

将会修复这个问题
